algoritmo "Senha do usuário"

// Disciplina: Lógica de Programação (LOPAL)
// Professor: Raul Porto Lopes
// Autor:Gabriel de Araujo Torres N°08
// Data atual: 13/04/2026

// Função: Verificação de senha.

var
senha, senhaaa, nomeUsuario: literal

inicio
// Entrada de dados
   senha<- ("acb23")
   escreval("Digite o seu nome de usuário")
   leia (nomeUsuario)
   escreval("Digite a senha do usuário: ")
   leia (senhaaa)
   limpatela
   // Variável
   se senha = senhaaa entao
   escreval("Senha correta!")
   escreva("...Logando...")
   senao
   escreva("Senha incorreta!")
   fimse
   
fimalgoritmo

